# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sttgRPC.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsttgRPC.proto\x12\x0eorialz.sttgRPC\"\x14\n\x05Sound\x12\x0b\n\x03\x62in\x18\x01 \x01(\x0c\"\x14\n\x04Text\x12\x0c\n\x04text\x18\x01 \x01(\t\"6\n\nStreamText\x12\r\n\x05start\x18\x01 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x05\x12\x0c\n\x04text\x18\x03 \x01(\t2\x8e\x01\n\x0cSpeechToText\x12\x45\n\x0ctoStreamText\x12\x15.orialz.sttgRPC.Sound\x1a\x1a.orialz.sttgRPC.StreamText(\x01\x30\x01\x12\x37\n\x06toText\x12\x15.orialz.sttgRPC.Sound\x1a\x14.orialz.sttgRPC.Text(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sttgRPC_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SOUND']._serialized_start=33
  _globals['_SOUND']._serialized_end=53
  _globals['_TEXT']._serialized_start=55
  _globals['_TEXT']._serialized_end=75
  _globals['_STREAMTEXT']._serialized_start=77
  _globals['_STREAMTEXT']._serialized_end=131
  _globals['_SPEECHTOTEXT']._serialized_start=134
  _globals['_SPEECHTOTEXT']._serialized_end=276
# @@protoc_insertion_point(module_scope)
