# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import orialz.sttgRPC_pb2 as sttgRPC__pb2


class SpeechToTextStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.toStreamText = channel.stream_stream(
                '/orialz.sttgRPC.SpeechToText/toStreamText',
                request_serializer=sttgRPC__pb2.Sound.SerializeToString,
                response_deserializer=sttgRPC__pb2.StreamText.FromString,
                )
        self.toText = channel.stream_unary(
                '/orialz.sttgRPC.SpeechToText/toText',
                request_serializer=sttgRPC__pb2.Sound.SerializeToString,
                response_deserializer=sttgRPC__pb2.Text.FromString,
                )


class SpeechToTextServicer(object):
    """Missing associated documentation comment in .proto file."""

    def toStreamText(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def toText(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpeechToTextServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'toStreamText': grpc.stream_stream_rpc_method_handler(
                    servicer.toStreamText,
                    request_deserializer=sttgRPC__pb2.Sound.FromString,
                    response_serializer=sttgRPC__pb2.StreamText.SerializeToString,
            ),
            'toText': grpc.stream_unary_rpc_method_handler(
                    servicer.toText,
                    request_deserializer=sttgRPC__pb2.Sound.FromString,
                    response_serializer=sttgRPC__pb2.Text.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orialz.sttgRPC.SpeechToText', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SpeechToText(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def toStreamText(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/orialz.sttgRPC.SpeechToText/toStreamText',
            sttgRPC__pb2.Sound.SerializeToString,
            sttgRPC__pb2.StreamText.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def toText(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/orialz.sttgRPC.SpeechToText/toText',
            sttgRPC__pb2.Sound.SerializeToString,
            sttgRPC__pb2.Text.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
